symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600
    throttle_limit: 60  # Reduce this to 60 seconds instead of 3600
    enable_garbage_collection: true
